---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kometa-trakt-sync
  namespace: default
  annotations:
    configmap.reloader.stakater.com/reload: "kometa-config kometa-libraries"
spec:
  schedule: "*/10 * * * *" # Every 10 minutes
  suspend: true
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 1200
      # Add TTL to keep jobs around for 4 hours (14400 seconds) after completion
      ttlSecondsAfterFinished: 14400
      template:
        spec:
          initContainers:
            - name: config-init
              image: busybox
              command:
                - /bin/sh
                - -c
                - |
                  # Create config with variables replaced using | as delimiter to avoid issues with special chars
                  sed -e "s|PLEX_TOKEN|$KOMETA_PLEX_TOKEN|g" \
                      -e "s|TMDB_API_KEY|$KOMETA_TMDB_API_KEY|g" \
                      -e "s|RADARR_API_KEY|$KOMETA_RADARR_API_KEY|g" \
                      -e "s|SONARR_API_KEY|$KOMETA_SONARR_API_KEY|g" \
                      -e "s|TRAKT_CLIENT_ID|$KOMETA_TRAKT_CLIENT_ID|g" \
                      -e "s|TRAKT_CLIENT_SECRET|$KOMETA_TRAKT_CLIENT_SECRET|g" \
                      -e "s|TRAKT_ACCESS_TOKEN|$KOMETA_TRAKT_ACCESS_TOKEN|g" \
                      -e "s|TRAKT_REFRESH_TOKEN|$KOMETA_TRAKT_REFRESH_TOKEN|g" \
                      -e "s|TRAKT_CREATED_AT|$KOMETA_TRAKT_CREATED_AT|g" \
                      -e "s|NOTIFIARR_API_KEY|$KOMETA_NOTIFIARR_API_KEY|g" \
                      /readonly-config/config.yml > /writable-config/config.yml
              env:
                - name: KOMETA_PLEX_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: kometa-secrets
                      key: PLEX_TOKEN
                - name: KOMETA_TMDB_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: kometa-secrets
                      key: TMDB_API_KEY
                - name: KOMETA_RADARR_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: kometa-secrets
                      key: RADARR_API_KEY
                - name: KOMETA_SONARR_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: kometa-secrets
                      key: SONARR_API_KEY
                - name: KOMETA_TRAKT_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: kometa-secrets
                      key: TRAKT_CLIENT_ID
                - name: KOMETA_TRAKT_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: kometa-secrets
                      key: TRAKT_CLIENT_SECRET
                - name: KOMETA_TRAKT_ACCESS_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: kometa-secrets
                      key: TRAKT_ACCESS_TOKEN
                - name: KOMETA_TRAKT_REFRESH_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: kometa-secrets
                      key: TRAKT_REFRESH_TOKEN
                - name: KOMETA_TRAKT_CREATED_AT
                  valueFrom:
                    secretKeyRef:
                      name: kometa-secrets
                      key: TRAKT_CREATED_AT
                - name: KOMETA_NOTIFIARR_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: kometa-secrets
                      key: NOTIFIARR_API_KEY
              volumeMounts:
                - name: config
                  mountPath: /readonly-config
                - name: writable-config
                  mountPath: /writable-config
          containers:
            - name: kometa
              image: kometateam/kometa:latest
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: writable-config
                  mountPath: /config/config.yml
                  subPath: config.yml
                - name: libraries
                  mountPath: /config/libraries
                  readOnly: true
                - name: logs
                  mountPath: /config/logs
              command:
                - /bin/sh
                - -c
              args:
                - |
                  python3 kometa.py --read-only-config --config /config/config.yml --run
          restartPolicy: OnFailure
          volumes:
            - name: config
              configMap:
                name: kometa-config
                items:
                  - key: config.yml
                    path: config.yml
            - name: writable-config
              emptyDir: {}
            - name: libraries
              configMap:
                name: kometa-libraries
            - name: logs
              emptyDir: {}
