---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kometa-letterboxd-sync
  namespace: default
  annotations:
    configmap.reloader.stakater.com/reload: "kometa-config"
spec:
  schedule: "*/5 * * * *" # Every 5 minutes
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      # Add TTL to keep jobs around for 4 hours (14400 seconds) after completion
      ttlSecondsAfterFinished: 14400
      template:
        spec:
          containers:
            - name: kometa
              image: kometateam/kometa:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: PLEX_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: kometa-secrets
                      key: PLEX_TOKEN
                - name: TMDB_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: kometa-secrets
                      key: TMDB_API_KEY
                - name: RADARR_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: kometa-secrets
                      key: RADARR_API_KEY
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: logs
                  mountPath: /config/logs
              command:
                - /bin/sh
                - -c
              args:
                - |
                  python3 kometa.py --config /config/config.yml --run
          restartPolicy: OnFailure
          volumes:
            - name: config
              configMap:
                name: kometa-config
            - name: logs
              emptyDir: {}
