---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kometa-letterboxd-sync
  namespace: default
  annotations:
    configmap.reloader.stakater.com/reload: "kometa-config kometa-libraries"
spec:
  schedule: "*/5 * * * *" # Every 5 minutes
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 1200
      # Add TTL to keep jobs around for 4 hours (14400 seconds) after completion
      ttlSecondsAfterFinished: 14400
      template:
        spec:
          initContainers:
            - name: config-init
              image: busybox
              command:
                - /bin/sh
                - -c
                - |
                  cat /readonly-config/config.yml | \
                  sed "s|\${PLEX_TOKEN}|$KOMETA_PLEX_TOKEN|g" | \
                  sed "s|\${TMDB_API_KEY}|$KOMETA_TMDB_API_KEY|g" | \
                  sed "s|\${RADARR_API_KEY}|$KOMETA_RADARR_API_KEY|g" > /writable-config/config.yml
                  echo "Config file prepared with environment variables"
                  echo "--- BEGIN CONFIG FILE CONTENT ---"
                  cat /writable-config/config.yml
                  echo "--- END CONFIG FILE CONTENT ---"
              env:
                - name: KOMETA_PLEX_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: kometa-secrets
                      key: PLEX_TOKEN
                - name: KOMETA_TMDB_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: kometa-secrets
                      key: TMDB_API_KEY
                - name: KOMETA_RADARR_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: kometa-secrets
                      key: RADARR_API_KEY
              volumeMounts:
                - name: config
                  mountPath: /readonly-config
                - name: writable-config
                  mountPath: /writable-config
          containers:
            - name: kometa
              image: kometateam/kometa:latest
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: writable-config
                  mountPath: /config/config.yml
                  subPath: config.yml
                - name: libraries
                  mountPath: /config/libraries
                  readOnly: true
                - name: logs
                  mountPath: /config/logs
              command:
                - /bin/sh
                - -c
              args:
                - |
                  echo "Verifying config file content:"
                  cat /config/config.yml
                  echo ""
                  echo "Starting Kometa with config file..."
                  python3 kometa.py --read-only-config --config /config/config.yml --run
          restartPolicy: OnFailure
          volumes:
            - name: config
              configMap:
                name: kometa-config
                items:
                  - key: config.yml
                    path: config.yml
            - name: writable-config
              emptyDir: {}
            - name: libraries
              configMap:
                name: kometa-libraries
            - name: logs
              emptyDir: {}
