apiVersion: v1
kind: Secret
metadata:
    name: kometa-secrets
    namespace: default
type: Opaque
stringData:
    PLEX_TOKEN: ENC[AES256_GCM,data:7CQN61LLBARlq+CCvGqRRxqvbIU=,iv:H0VnA6MDtXIyQokq3ygDeDaWbEWTdyydBtWdwVxX+fg=,tag:TdZc+B0ZsjcHuah+l65hbQ==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:1KHuw1PrxviD2VnVMliFV+RemPPOhan+BrAIhztCv20=,iv:FM3JPfotCSw8Fftv609tpCJLumi0Wva3ExnIYlpGzeg=,tag:p1etO+Z9U5uVqgfKvtN7uw==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:w61HDJ0qynZaGy0K1Fad/uIqOo0kVEzZkxj6AqaF1a4=,iv:6RiM/pSKrQBQC6HVpuogZJQZfK2IkzySySCdKSRXL1o=,tag:28Z+vbg+/n1ipZSYAwadjA==,type:str]
    TRAKT_CLIENT_ID: ENC[AES256_GCM,data:MoJ/PdftOhkyn0N9OdZsPrv04jFV3RlXrh3lWOIB82ZyCsdLeVPwGMqjaUo+zVI5/Ibywwbv7zXv8Oey6BhP8w==,iv:ZAQ7pYHuRAlKjK/udrfuFHylTMWza5jKsfW/5u2HObI=,tag:HznpR/4yMMX2Z8jjx0kXPg==,type:str]
    TRAKT_CLIENT_SECRET: ENC[AES256_GCM,data:dmrRDUIT9WD4LJBoJjedGXVSmkD/DVcIgc7ZAikwGG1t4TG6HSGGX0hDwW9ofbvmnDUV6Bt0BirHmQACeoQ8rg==,iv:dGmMbIOPVGUkSs1rTZJWEpV30MXT0z+8YToWhwjpNJQ=,tag:ddxi/2ghhwOpJky3hD1uAw==,type:str]
    TRAKT_ACCESS_TOKEN: ENC[AES256_GCM,data:NzYD3SXgnEyvaf804D4DQ4KBnL7Z5qErP5RvZe25fV996tUgWKVNPfiKL92dzmB5lqu9xzDe3NZCF7sVGh1MSA==,iv:57oQRtxL+TdncCMRA3hlKhWxsK2eCQMQiaw3xm7K1uU=,tag:K590CizkAiInCWgU4UgqNg==,type:str]
    TRAKT_REFRESH_TOKEN: ENC[AES256_GCM,data:9B+6gdlFgOHfUkYtaIB9LvrFjM+IyAYgoHwhGn/fdbFXIrYcZg/fyKK0/JBqY/ffLbUODQ09KAWEso03/sSgYA==,iv:tQq7a17GFwpOLIbtfOA0aSsI2urpmsczz8O1LjncYew=,tag:PD9b6X00fr7w/a6xl/Qjfw==,type:str]
    TRAKT_CREATED_AT: ENC[AES256_GCM,data:VBw1f45mqhvvLA==,iv:bw+quTmVWWfbb+K2HW5mYxOPDQnd4pNW7GRXAmZwTWo=,tag:wgWt5WccpoLwQFdaliSZ2A==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:WccAfbxe/0Lu4xhobs4QeA/IfCf6zrCp/NBUIbPJN88=,iv:mVwhRLzuaOXtjpUmkRtb5tX5n6O3q/ZBiNfLKI3afFw=,tag:HUEigfezFQLr1yyzrP0XuA==,type:str]
    NOTIFIARR_API_KEY: ENC[AES256_GCM,data:knDiN6P0S2xcp9DTxMdlMC3v3pAbWSEnHTDGop0J57vJvWjR,iv:iapTQk/dPBwNId7W5bwxpkuhY2ifJAZQtB6Rj12vlP8=,tag:tjYjvX5e/1fMvTB/gJp17w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7u0qylrvurhvcaxjurqrflx2ey96lx5gzar6r8d9ctl6rzqg5gqu94ek4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuL1FDZnphTnNJLzJBUUVr
            VGhSY3BUSVhrbmhXbWJWa3JMTkZ3cS9xTDNFCk9qazF6UjRPUVoyMjVsZVBRZVRJ
            YXJlYkFXcGNwY3BaNEx4WnFOTEJ6UmMKLS0tIC90Q2Z3ekxFWWc0cUVQcUlDcmlK
            eE5LUkhrRTlMVFBUTWdtek0yUXhTb2sKp7hdI2wbaI7mqxMLgoOgDWPbGcdh0wsI
            jxE/QEj+4e/vK/L0t/4uhA8wwXNMwgG+bxvtfuYq+CdszQYWRllJmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T17:05:34Z"
    mac: ENC[AES256_GCM,data:Nkq0wgdSbMxiuJu7GzYMzeT8aMJmakrvYUSycsztxZvQASQEC6/hWca9VKvoU5CUovRO6j08jTnu3z0XZIOo1gRFyMuRvCtCRV8NgVIg9hODoU5FW4A2ysm6jS0QLM9UlesJ9Vv7tyOEpWwHDDumw10nSENWmALGAfYitXWAwgA=,iv:XtNXUPmqPT9dXAt0QEwnCSebegWjsIzPc0nC1r7Whao=,tag:gAenLl3AC1wGbbkSfFebOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
