apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:hgE5mQm6h7RJ,iv:CEbiM6k4FbS6uVpLLDAVd9rWiKobYpAU6l+fbCRJ4vg=,tag:chz8aidQ1nLmqhL+jFlFHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7u0qylrvurhvcaxjurqrflx2ey96lx5gzar6r8d9ctl6rzqg5gqu94ek4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNERkdGZCMW0wS3JCTy9J
            R29KbXVWOXFUNEJLOUtlMEhZaWN2TUdOS1Q0CnlScWZvQnF0Q3hTZjRFQWcyTWxy
            MTJmendDTGNMb1pNQW5QWkhuMWlqN3MKLS0tIEcvdUUvQm9xekRVSU1nOWtxV04r
            REV2QitDdjZQS1ZOUm81ek1vYmFQR2sK9+SyJp6O7QjtN17nD3IzQg9D0mkRQu4T
            s/8ZD3lZwaTvZcrakDn08j5jUHfz5WJbism39QmwJam1Folns4hhtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T17:13:07Z"
    mac: ENC[AES256_GCM,data:LimPYs0DFzs51eQEHrfZRxpXMW5LNa4gOddlXalG4O1/oUxBnWMpcBtmOfWMHLpLFz1A/NvUgmvJ81tGN9yALSG9ArVVCGEYtYWFBSYxi/zbzVslBRgyh2itthRlRFIeXuU24MWsAWIQ1k0TTzVnwx8PHGndxdNhB599dPNsWmQ=,iv:oXGfSkaroK2BwN/ItU8Z0iILXQyA2CWa4oj0PSNMX/Y=,tag:C0orxulVpA6FbSUbKlxrMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
