apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:BwKgSeA=,iv:l1lsSTjhseTPp9COONgrppjmICX5trOl3O/rjg0xq2s=,tag:SnMC+23DLjjm+75dDbSZSA==,type:str]
    admin-password: ENC[AES256_GCM,data:hgE5mQm6h7RJ,iv:CEbiM6k4FbS6uVpLLDAVd9rWiKobYpAU6l+fbCRJ4vg=,tag:chz8aidQ1nLmqhL+jFlFHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7u0qylrvurhvcaxjurqrflx2ey96lx5gzar6r8d9ctl6rzqg5gqu94ek4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNERkdGZCMW0wS3JCTy9J
            R29KbXVWOXFUNEJLOUtlMEhZaWN2TUdOS1Q0CnlScWZvQnF0Q3hTZjRFQWcyTWxy
            MTJmendDTGNMb1pNQW5QWkhuMWlqN3MKLS0tIEcvdUUvQm9xekRVSU1nOWtxV04r
            REV2QitDdjZQS1ZOUm81ek1vYmFQR2sK9+SyJp6O7QjtN17nD3IzQg9D0mkRQu4T
            s/8ZD3lZwaTvZcrakDn08j5jUHfz5WJbism39QmwJam1Folns4hhtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T17:28:16Z"
    mac: ENC[AES256_GCM,data:qpklNMnGLKVummlbGtSI1vR3FG3KwsFlFEx8k2QpuUlujvYBm7UbKnalUApa4TJzheD7sw3L47Z15QBWb2SD2vvXGaC3DW5XZz5Tg+mam9DTXt2DMW+NBFw9CMI8moqkf6kz/yKcBDrkBlW6aUJH3cG5gIQABYrOj2s28y+bHwM=,iv:106T81HExnkMPLO62CcidZmY5qx1jvsU7UB3g06FnOQ=,tag:z3K9wi2JcM8Cew03H5SKfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
