---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: whisper2
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
    image:
      repository: rhasspy/wyoming-whisper
      tag: latest
    args:
      - --model
      - medium
      - --language
      - en

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${WHISPER2_LB}"
        externalTrafficPolicy: Local
        ports:
          http:
            enabled: true
            port: 10300
            protocol: TCP

    resources:
      requests:
        cpu: 1000m
        memory: 2048Mi
      limits:
        memory: 4096Mi

    persistence:
      config:
        enabled: true
        existingClaim: whisper2-data
        mountPath: /data
