---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-data-v2
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
