---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: adguard/adguardhome
              tag: latest
              pullPolicy: IfNotPresent
            env:
              TZ: "Europe/Dublin"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 80
                  initialDelaySeconds: 3
                  periodSeconds: 3
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 80
                  initialDelaySeconds: 3
                  periodSeconds: 3
                  timeoutSeconds: 5
                  failureThreshold: 3
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 80
                  initialDelaySeconds: 3
                  periodSeconds: 3
                  timeoutSeconds: 5
                  failureThreshold: 3
    service:
      main:
        controller: main
        type: LoadBalancer
        loadBalancerIP: "${ADGUARD_LB_IP}"
        externalTrafficPolicy: Local
        ports:
          http:
            enabled: true
            port: 80
            protocol: TCP
            targetPort: 80
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
    persistence:
      config:
        enabled: true
        existingClaim: adguard-config-v2
        globalMounts:
          - path: /opt/adguardhome/conf
      data:
        enabled: true
        existingClaim: adguard-data-v2
        globalMounts:
          - path: /opt/adguardhome/work
