---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: adguard/adguardhome
              tag: latest
              pullPolicy: IfNotPresent
            env:
              TZ: "Europe/Dublin"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
    service:
      main:
        controller: main
        ports:
          http:
            port: 3000
            protocol: HTTP
      dns-tcp:
        controller: main
        type: LoadBalancer
        loadBalancerIP: "${ADGUARD_LB_IP}"
        externalTrafficPolicy: Local
        ports:
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
      dns-udp:
        controller: main
        type: LoadBalancer
        loadBalancerIP: "${ADGUARD_LB_IP}"
        externalTrafficPolicy: Local
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.ashleydeane.me"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host "adguard.ashleydeane.me"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: adguard-tls
    persistence:
      config:
        enabled: true
        existingClaim: adguard-config
        globalMounts:
          - path: /opt/adguardhome/conf
      data:
        enabled: true
        existingClaim: adguard-data
        globalMounts:
          - path: /opt/adguardhome/work
