tunnel: 644b31f5-319e-4f2d-a1bf-71acb67ee92f
credentials-file: /etc/cloudflared/credentials.json
ingress:
  - hostname: radarr.ashleydeane.me
    service: http://radarr.home:7878
  - hostname: sonarr.ashleydeane.me
    service: http://sonarr.home:8989
  - hostname: truenas.ashleydeane.me
    service: http://freenas.home
  - hostname: sonarr4.ashleydeane.me
    service: http://10.0.0.142:8989
  - service: http_status:404
