tunnel: 644b31f5-319e-4f2d-a1bf-71acb67ee92f
credentials-file: /etc/cloudflared/credentials.json
ingress:
  - hostname: truenas.ashleydeane.me
    service: http://freenas.home
  - service: http_status:404
