---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ./helm-release.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - name: cloudflared-config
    files:
      - config.yaml=./config.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
