---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: piper
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
    image:
      repository: rhasspy/wyoming-piper
      tag: latest
    args:
      - --voice
      - en_GB-vctk-medium

    service:
      main:
        ports:
          http:
            enabled: true
            port: 10200
            protocol: TCP

    persistence:
      config:
        enabled: true
        existingClaim: piper-data
        mountPath: /data
