# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: kube-system
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:kW/zbGnYywf2rQ92CN9RkJR9kARt7On7YA==,iv:3mctCuU4lu4No4Vff3E6S+T3Oh1HGp6GimWvReBOBO8=,tag:oKpadD1heLkALcRJfAVBMw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:MMcIZBQaX5iiFcGobxwWQ5ZXXtYGaeNVfkj4lh+D1zzOEMPPYQ==,iv:U3PGNJstRIGGgy1YlHoQuQWPF+vbtan6pAeNb+DvLYs=,tag:aFuTYI/VqGiAZsNgS4a+uw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:oNIiClW4JkmedTn/Oe6hVcryzg==,iv:XRz8gAzn5WJurw3/1OjCJgmNnam31FNEFMGkffVpb5g=,tag:DwwNnYEqZYnzNtYfGR1Evg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7u0qylrvurhvcaxjurqrflx2ey96lx5gzar6r8d9ctl6rzqg5gqu94ek4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwc2hvUk1CTWNKQ28xa1hG
            YkM1ZVlVZDI4eHRFUGNqK2dZMHBEMElBaVVNCkdXS3B2Um9YMGtiVEhaYk56Vkw2
            WGh2T2lVR2xsRkc4aWhWYjRIems5dTgKLS0tIC95L2VDM25qMW5DRlJXblMrTFJa
            WWpBbzAxSHdOcTVOV3ZDb2RIZDk5SFEKM8nLnxm4Wr1ZQXP4CGs8sv6e2zkagYCQ
            pg+STQn7+87kaiWwrLnd2yghC6gMTNHymro974cwS36db1fLb2CFAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-11T22:44:45Z"
    mac: ENC[AES256_GCM,data:bxAfcHWmJ3fR2QqeZWDTBI7HWqKl85Ij5QbL6efPfEvZjoq9H8gDojUKUFw0zs+hn/az0OE18j5mVMP9nuYp4yor7qgNtgciQK/QjYjjUxZ5tAFjXnpiMe5rO4bMYfFiHE/MEA7shdL78FdT1f1axZ9qVteKRavbAr2/29jHjXE=,iv:LVaSnJBIU2Z8vlmgEaoq1GisSxqEYMjuFsniPoNIPXg=,tag:wrX5ao7NPDuffeVclLkizw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
