apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-pvc.yaml
  - config-pvc-minecraft-paper.yaml
  # - minecraft-vanilla.yaml
  - minecraft-paper.yaml
  - rcon-web-admin.yaml
  - secret.sops.yaml
