apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-pvc-minecraft-paper.yaml
  - minecraft-paper.yaml
  - rcon-web-admin.yaml
  - config-pvc-minecraft-create.yaml
  - minecraft-neoForge-create.yaml
  - rcon-web-admin-create.yaml
  - secret.sops.yaml
