apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-pvc-minecraft-paper.yaml
  - minecraft-paper.yaml
  - rcon-web-admin.yaml
  # Fix it by create a volume / share in freenas with the mods, using something like https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/#manual-downloads
  # might be handy to use freenas for the backup volume as well
  - config-pvc-minecraft-create.yaml
  - minecraft-neoForge-create.yaml
  - config-pvc-minecraft-create-modpack.yaml
  - minecraft-create-modkapck.yaml
  - rcon-web-admin-create.yaml
  - secret.sops.yaml
