---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-paper
  namespace: games
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: itzg/minecraft-server
      tag: 2022.16.0-java17
    resources:
      limits:
        memory: 8Gi
      requests:
        cpu: 1000m
        memory: 4Gi
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false
    extraEnv:
      TZ: "Ireland/Dublin"
      ENABLE_ROLLING_LOGS: true
    persistence:
      dataDir:
        enabled: true
        existingClaim: minecraft-paper-data
    serviceAnnotations:
      metallb.universe.tf/loadBalancerIPs: "${MINECRAFT_PAPER_LB}"
    minecraftServer:
      eula: true
      version: 1.19.2
      type: PAPER
      difficulty: normal
      ops: "bbbiiittt"
      pvp: true
      motd: "Minecraft 1.19.2 using Paper"
      worldSaveName: default
      viewDistance: 16
      forceReDownload: true
      memory: 4096M
      jvmXXOpts: "-Xms4G -Xmx4G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1"
      rcon:
        enabled: true
        serviceType: ClusterIP
      serviceType: LoadBalancer
      extraPorts:
        - name: metrics
          containerPort: 9225
          protocol: TCP
          service:
            enabled: true
            embedded: false
            type: ClusterIP
            port: 9225
          ingress:
            enabled: false
        - name: map
          containerPort: 8123
          protocol: TCP
          service:
            enabled: true
            embedded: false
            type: ClusterIP
            port: 8123
          ingress:
            ingressClassName: "nginx"
            enabled: true
            annotations:
              # cert-manager.io/cluster-issuer: letsencrypt-production
              # external-dns.home.arpa/enabled: "true"
              # external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
              # hajimari.io/appName: Minecraft
              # hajimari.io/enable: "true"
              # hajimari.io/icon: simple-icons:minecraft
              # hajimari.io/group: games
            hosts:
              - name: &host "minecraft-paper.${SECRET_DOMAIN}"
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: "minecraft-paper.${SECRET_DOMAIN}"
                hosts:
                  - *host