---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-paper
  namespace: games
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      # https://github.com/itzg/minecraft-server-charts/tree/master/charts/minecraft
      chart: minecraft
      version: 4.19.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: itzg/minecraft-server
      tag: 2024.4.0-java21
    resources:
      limits:
        memory: 8Gi
      requests:
        cpu: 1000m
        memory: 4Gi
    podSecurityContext:
      runAsUser: 1000
      fsGroup: 1000
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false
    extraEnv:
      MODS: "https://github.com/spnda/BlockProt/releases/download/1.2.1/blockprot-spigot-1.2.1-all.jar,https://mediafilez.forgecdn.net/files/5442/792/Dynmap-3.7-beta-6-spigot.jar,https://mediafilez.forgecdn.net/files/3635/984/Dynmap-WorldGuard-1.4-beta-1.jar,https://github.com/EssentialsX/Essentials/releases/download/2.20.1/EssentialsX-2.20.1.jar,https://mediafilez.forgecdn.net/files/5443/866/worldedit-bukkit-7.3.4-beta-01.jar,https://mediafilez.forgecdn.net/files/5477/815/worldguard-bukkit-7.0.11-beta1-dist.jar,https://hub.bg-software.com/job/WildLoaders%20-%20Stable%20Builds/1/artifact/target/WildLoaders-2023.3.jar"
      SPIGET_RESOURCES: "23307,28140,32129,64346,60383"
      TZ: "Ireland/Dublin"
      ENABLE_ROLLING_LOGS: true
    persistence:
      dataDir:
        enabled: true
        existingClaim: minecraft-paper-data-v2
    mcbackup:
      enabled: true
      persistence:
        backupDir:
          enabled: true
          exisitingClaim: minecraft-paper-data-backup-v2
    serviceAnnotations:
      metallb.universe.tf/loadBalancerIPs: "${MINECRAFT_PAPER_LB}"
    minecraftServer:
      eula: true
      version: "1.21"
      type: PAPER
      difficulty: normal
      ops: "bbbiiittt"
      pvp: true
      motd: "Minecraft 1.21 using Paper"
      worldSaveName: default
      viewDistance: 16
      forceReDownload: true
      memory: 4096M
      jvmXXOpts: "-Xms4G -Xmx4G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1"
      rcon:
        enabled: true
        existingSecret: minecraft-rcon-credentials
        serviceType: ClusterIP
      serviceType: LoadBalancer
      extraPorts:
        - name: metrics
          containerPort: 9225
          protocol: TCP
          service:
            enabled: true
            embedded: false
            type: ClusterIP
            port: 9225
          ingress:
            enabled: false
        - name: map
          containerPort: 8123
          protocol: TCP
          service:
            enabled: true
            embedded: false
            type: ClusterIP
            port: 8123
          ingress:
            ingressClassName: "nginx"
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-production
              external-dns.home.arpa/enablerd: "true"
              external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
              hajimari.io/appName: Minecraft
              hajimari.io/enable: "true"
              hajimari.io/icon: simple-icons:minecraft
              hajimari.io/group: games
            hosts:
              - name: &host "minecraft.${SECRET_DOMAIN}"
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: "minecraft.${SECRET_DOMAIN}"
                hosts:
                  - *host
