---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rcon-web-admin
  namespace: games
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: rcon-web-admin
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    resources:
      requests:
        memory: 512Mi
        cpu: 200m
      limit:
        memory: 512Mi
        cpu: 400m
    ingress:
      enabled: true
      hosts:
        - host: &host "rcon.${SECRET_DOMAIN}"
          path: /
          pathType: Prefix
      tls:
        - secretName: "rcon-server-tls"
          hosts:
            - *host
    rconWeb:
      isAdmin: true
      passwordExistingSecret: rcon-password
      passwordKey: rcon-password
      rconHost: minecraft-minecraft-rcon
      rconPasswordExistingSecret: rcon-password
    extraEnv:
      TZ: ${TZ}