---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rcon-web-admin
  namespace: games
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: rcon-web-admin
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    resources:
      requests:
        memory: 512Mi
        cpu: 200m
      limits:
        memory: 512Mi
        cpu: 400m
    ingress:
      enabled: true
      host: &host "rcon.${SECRET_DOMAIN}"
      tls:
        - secretName: "rcon-server-tls"
          hosts:
            - *host
    rconWeb:
      isAdmin: true
      passwordExistingSecret: minecraft-rcon-credentials
      passwordKey: rcon-password
      rconHost: minecraft-paper-minecraft-rcon.games.svc.cluster.local
      rconPasswordExistingSecret: minecraft-rcon-credentials
      rconPasswordKey: rcon-password
    extraEnv:
      TZ: "Ireland/Dublin"
