---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: notifiarr
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: golift/notifiarr
      tag: latest
    env:
      TZ: "Europe/Dublin"
    envFrom:
      - secretRef:
          name: notifiarr-secrets
    service:
      main:
        ports:
          http:
            port: 5454
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "bell-ring"
        ingressClassName: "nginx"
        hosts:
          - host: &host "notifiarr.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
            secretName: "notifiarr-tls"
    persistence:
      config:
        enabled: true
        existingClaim: notifiarr-config
        mountPath: /config
