apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-config
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
