---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: louislam/uptime-kuma
              tag: 1.23.16
            env:
              TZ: "${TIMEZONE}"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 500Mi
    service:
      app:
        controller: main
        ports:
          http:
            port: 3001

    persistence:
      config:
        enabled: true
        existingClaim: uptime-kuma-config
        mountPath: /app/data

    ingress:
      main:
        enabled: true
        className: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "eos-icons:monitoring"
          hajimari.io/appName: Uptime-Kuma
        hosts:
          - host: &host "status.${SECRET_DOMAIN}"
        paths:
          - path: /
            service:
              identifier: app
              port: http
        tls:
          - hosts:
              - *host
            secretName: "status-tls"
