# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt
    namespace: default
stringData:
    ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:8tl6g3D4XEU=,iv:U/G7qLpXrgzPiTr+mBBfrPO3X1X3Zn/u9jeDYsRQ41g=,tag:3dGtTeqfLUvwcP0N/6fPfg==,type:str]
    ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:+kDIa8sb3iQlQGQ=,iv:w/KDvi1XYcBfuUKLcHVaVjbXLq+XH0+KQKwOXAI40Kg=,tag:cl9uoqWR7z6qT97DusL98w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7u0qylrvurhvcaxjurqrflx2ey96lx5gzar6r8d9ctl6rzqg5gqu94ek4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bTBhbC9FaVR5RGJ5WC9R
            ODFobXBXZ1lZSnd3akgwODNSVmlBRWJuZ3dNCjBaeHNPekUyL1h6V0xMek1XK1Z2
            N2VITm02bHVjNEo0bFdaYXplZjNTWFkKLS0tIG9TM2lHUDd0N1BwVWZBemtvcXAz
            MkNFK3hZNHdlSFFKMjlBRWlPUUlMelUK9jhH6RhDS1pEwfK0AwCXvoa9x5FDfBKq
            qPImFzPUxkOI4ljRRQMzc7zi70ka2lEj4PoimHXDEFHTEbtrB7aZ0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-04T15:17:23Z"
    mac: ENC[AES256_GCM,data:hNa97azFy9WZyMWGISxvZpN2q/+uFsKaZw20OiXwqmxiyDF+wEMTWuBaPxRPPQd4Dr96IBQipeRrgYG+JQsgyIPwxg4kfwdBvrezYDmDUZQngQwNLLfLBm5Nr6eizxwx4ztKFAGqu+rO7bs+WsGYpD276A+63awbqfqgTh8DNqo=,iv:986gPMVWl3gW94bYhxhRE9t0K6iCFbCHi+0LKXq5fG0=,tag:buewRxryWvpX4TYwCP0QGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
