apiVersion: v1
kind: Secret
metadata:
    name: grafana-mcp-token
    namespace: monitoring
stringData:
    api-key: ENC[AES256_GCM,data:yQiexyDBQc6sQIZrzQZK6Q/2XIgNUPPa8Lf5bMqtr3NQG0BW+RnTUa5/kVpO5A==,iv:1ia9QBmrsGKq8ZPYZQd15ZoC/gut6WgslgVjZy7qw7E=,tag:Z4TMOMZYv/DfEjHYOsobPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7u0qylrvurhvcaxjurqrflx2ey96lx5gzar6r8d9ctl6rzqg5gqu94ek4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNjIzNnFJNkZpOGpCcEdF
            MDRhUjNoaG5heU1kZ1pTN093ZWVLS1FmYjM4Clp6emo4UnQzeDFDSDNTamw2MVRr
            bGpubUpETFFwTmFMd2ZQMFV0L1k4NXMKLS0tIDk3U2NtcWJJMk5KWGlOWHRUN1VF
            VUdJVVBrSTEydlN0ZmlvcVY0ZTZCZVEK+KC0cT3ZnEPySzuWPapokGaUJnCtFRPo
            fLz/qSl7XMwPcSduq/SwKlUYLF819H8tvDq6es2dawN6CwDixcYZ0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T22:14:34Z"
    mac: ENC[AES256_GCM,data:Guttl6yXcTsH4xDpVWRMAdubzu9ng3xOHvYEYna8Rhcx7wbenrwndqFvvZ7QBuaVM2TKYEVqVqgNm4jVOa0frl+eQn7mrjK4/TNz3SkQoAxLWrH1qDvZwJj1jy0/lhJjDNQu0oOwo4u/ppfdt7rseYgdxqLvLbD+axAKMQdllE4=,iv:XyS+jchSkDeFkFSCzeTWeFRveuNTt4MABjvHRIWvwAM=,tag:R2SIYbLXxc6p3t0FRe7jBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
