---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app satisfactory
  namespace: games
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: wolveix/satisfactory-server
      tag: latest
    env:
      DATA_FOLDER: "config"
      AUTOPAUSE: false
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: "${SATISFACTORY_LB}"
        ports:
          http:
            enabled: false
            primary: false
          beacon:
            enabled: true
            port: 7777
            protocol: TCP
          game:
            enabled: true
            port: 7777
            protocol: UDP
    persistence:
      config:
        enabled: true
        existingClaim: satisfactory-data-v1
        mountPath: /config
      server-cache:
        enabled: true
        existingClaim: satisfactory-gamedata-v1
        mountPath: /config/gamefiles
    probes:
      startup:
        enabled: false
      liveness:
        enabled: false
      readiness:
        enabled: false
    resources:
      requests:
        cpu: 200m
        memory: 6740Mi
