apiVersion: v1
kind: Secret
metadata:
    name: exportarr-secrets
    namespace: default
type: Opaque
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:pyqvHSYU3Hzt8MFW+DRuV32BCNeDqA6nM0V2cuMcGXg=,iv:rt/b4vbXVT4nDA+ZbelPhLm9rfGu29FPRqy9gFBBRDw=,tag:OFkwLjgcqZJYe5K3YlSN7g==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:rLuSiWIDHE0rqdS1S/AdOxDzFVyAJRrS3YwPX/W20jM=,iv:3RKE1V+pYs5FsO/Xhscog03pICD6AOAJmDQfqt5D8Ik=,tag:KF1t12a5iuv8OcrQI/OCzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7u0qylrvurhvcaxjurqrflx2ey96lx5gzar6r8d9ctl6rzqg5gqu94ek4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvR3JVMFVVTGwweVZpMVN1
            VlZxNlc3R2xnZGxMbU4rK3NmeXFoS2dlbEhjCjZZUkNPUkxjekJoMzhBRGtIaVZF
            WjhjTUF5eFdaQUxreUtNUitBS3h3VmcKLS0tIHFCN3hueHJWblVPWkltTGtpOW04
            bXRkNmlzZVhQaDd5d0NJZ2F6MDNkejgKQRlatDTUwQKt6+mx2WEeepVr/IghkHNJ
            4SDnkSq3MJbiY7er5/6Xw8EHz5V2d2yQ6pLj9wNj/0olnoHvLasXnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T15:34:58Z"
    mac: ENC[AES256_GCM,data:QtK7akC2tTjLXyxsl9TjVub0BEWGjmdFt+sQX2wuHbWcpoxLOouZEu/E4OeNoPGZKXrn9SRdl1UPkUqN5BTtSyV/7LO2g63Edmp4DttjouxfYbU2oitCGF3inAhxU43FMt1le/fe6ChsbzU+cPxLF6ToeRMU+lglI/24/zJl8S8=,iv:3aoVhpybs5IKT+Rrt6ZcKxtkeNrrvClyc/eFHdx6DfM=,tag:rhUFk4TDKUIn2bXYEBr4Bg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
