---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2023.6.2
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config
      # deploy-key:
      #   enabled: true
      #   type: secret
      #   name: git-ssh-keys
      #   readOnly: true
      #   defaultMode: 0600
      #   subPath:
      #     - path: GH_DEPLOY_KEY
      #       mountPath: /root/.ssh/id_rsa
    env:
      TZ: "Europe/Dublin"
    service:
      main:
        ports:
          http:
            port: 8123
      node:
        enabled: true
        controller: main
        type: NodePort
        ports:
          hue:
            port: 30080
            targetPort: 30080
            nodePort: 30080
      lb:
        type: LoadBalancer
        loadBalancerIP: "${HASS_LB}"
        externalTrafficPolicy: Local
        ports:
          http-lb:
            enabled: true
            port: 8123
            protocol: HTTP

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "home-assistant"
        hosts:
          - host: &host "hass.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
            secretName: "hass-tls"
    resources:
      requests:
        cpu: 500m
        memory: 1024Mi
      limits:
        memory: 2048Mi
    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.9.1
        volumeMounts:
          - name: config
            mountPath: /config
        # git:
        #   # -- Existing secret containing SSH private key
        #   # The chart expects it to be present under the `id_rsa` key.
        #   # https://github.com/bjw-s/helm-charts/blob/ae4233c77f91d15a93fd20a2245113acf9254b54/charts/library/common/templates/addons/code-server/_container.tpl#L37
        #   deployKeySecret: git-ssh-keys
        ingress:
          enabled: true
          ingressClassName: "nginx"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-production"
            hajimari.io/enable: "true"
            hajimari.io/icon: vscode-icons:file-type-vscode
            hajimari.io/info: Home-Assistant Editor
            hajimari.io/group: automation
          hosts:
            - host: &codeHost "editor.hass.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - *codeHost
              secretName: "hass-editor-tls"
