
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  values:
    service:
      lb:
        type: LoadBalancer
        loadBalancerIP: "${HASS_LB}"
        externalTrafficPolicy: Local
        ports:
          http-lb:
            enabled: true
            port: 8123
            protocol: HTTP
          hue-lb:
            port: 80
          udp-10400:
            port: 10400
            protocol: UDP
          udp-10401:
            port: 10401
            protocol: UDP
          udp-10402:
            port: 10402
            protocol: UDP
          udp-10403:
            port: 10403
            protocol: UDP
          udp-10404:
            port: 10404
            protocol: UDP
          udp-10405:
            port: 10405
            protocol: UDP
          udp-10406:
            port: 10406
            protocol: UDP
          udp-10407:
            port: 10407
            protocol: UDP
          udp-10408:
            port: 10408
            protocol: UDP
          udp-10409:
            port: 10409
            protocol: UDP
          udp-10410:
            port: 10410
            protocol: UDP
          udp-10411:
            port: 10411
            protocol: UDP
          udp-10412:
            port: 10412
            protocol: UDP
          udp-10413:
            port: 10413
            protocol: UDP
          udp-10414:
            port: 10414
            protocol: UDP
          udp-10415:
            port: 10415
            protocol: UDP
          udp-10416:
            port: 10416
            protocol: UDP
          udp-10417:
            port: 10417
            protocol: UDP
          udp-10418:
            port: 10418
            protocol: UDP
          udp-10419:
            port: 10419
            protocol: UDP
          udp-10420:
            port: 10420
            protocol: UDP
          udp-10421:
            port: 10421
            protocol: UDP
          udp-10422:
            port: 10422
            protocol: UDP
          udp-10423:
            port: 10423
            protocol: UDP
          udp-10424:
            port: 10424
            protocol: UDP
          udp-10425:
            port: 10425
            protocol: UDP
          udp-10426:
            port: 10426
            protocol: UDP
          udp-10427:
            port: 10427
            protocol: UDP
          udp-10428:
            port: 10428
            protocol: UDP
          udp-10429:
            port: 10429
            protocol: UDP
          udp-10430:
            port: 10430
            protocol: UDP
          udp-10431:
            port: 10431
            protocol: UDP
          udp-10432:
            port: 10432
            protocol: UDP
          udp-10433:
            port: 10433
            protocol: UDP
          udp-10434:
            port: 10434
            protocol: UDP
          udp-10435:
            port: 10435
            protocol: UDP
          udp-10436:
            port: 10436
            protocol: UDP
          udp-10437:
            port: 10437
            protocol: UDP
          udp-10438:
            port: 10438
            protocol: UDP
          udp-10439:
            port: 10439
            protocol: UDP
          udp-10440:
            port: 10440
            protocol: UDP
          udp-10441:
            port: 10441
            protocol: UDP
          udp-10442:
            port: 10442
            protocol: UDP
          udp-10443:
            port: 10443
            protocol: UDP
          udp-10444:
            port: 10444
            protocol: UDP
          udp-10445:
            port: 10445
            protocol: UDP
          udp-10446:
            port: 10446
            protocol: UDP
          udp-10447:
            port: 10447
            protocol: UDP
          udp-10448:
            port: 10448
            protocol: UDP
          udp-10449:
            port: 10449
            protocol: UDP
          udp-10450:
            port: 10450
            protocol: UDP