# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: git-ssh-keys
    namespace: default
stringData:
    id_rsa: ENC[AES256_GCM,data:SoCgFtbXpQkFGqraSoAjHgJWutB6CXHegPla75ZyewRs+EZ8M6xPVCmPZ9rolIgWcKpBpi1TRviDvMMskpMe6xvpZwIvfsRnZ29l37GVcqiRGTbKFKVB/RzBW/WDpyOq6mMAD62rUedF6DgN6MR1lXEiFcGMo4peLYDcu1ADxbcML4npQKNkMtdk86kicncmPbxTAwvR61gxoYrnD8+4m8bQFjaVhY5jefHFP5lhYhZ7pAV7XT26Czc/bgucRemHVB40m3rcGz+Gr5GzaRxwGFqjfsUN2hwO4sZViNaL3bLUoevum07oPyPqhRaX19v1/nI2O26lG7G200KgV3zDgrDNlGrPxorrp1xHJPDe4W3ayg7NO3k+jiVm+xho0dHkHmiAhkzx1pzUoWeiDgJI3crSmpcSs3ivGgJcB1g2e0F9RDVa+hKLleIW6egDOc3myyBYdY3x0uxDcWmgbILrcXbkQJR4ULtGYx6xK5xmbQgwmpgCDTzlP+rt0tMLmouJxGR/OWU2u3bGOebhrqzBMUTm4GUJIw5qNhqw,iv:IUY8Qct0GiL1o4NoNz2A4vCenvaGtgh6SQHGLSf2cSk=,tag:j4buLXNs/Q8dy1zKGzIsiA==,type:str]
    GH_DEPLOY_KEY: ENC[AES256_GCM,data:TBmLtwUWQyo1G/MbT/wHD0nXqzHxH1FLjKVktN2g1dylWP6enYJnhGyRJU1kDN6sdiptmf/Yzl2YsOl6agA9Fx/jq8Sj8nJWKcPgZnyYkIVbR0tvkgKRZx/4aH1HglUyvn05ytxTCeBWv8K+8F6cuDvN7sx+YfRaYKlWUQ/5RLVPxcg6F3xk+9TEekILhJ2N0mGCsO6Fc7mA//yEqmN6HNEQYyT3pnGOqbo8p/0ksK1w++Cu8si61B6Nb1xaFyvddyWg797yf7lNrVQydLGqs2574NkB++MEzvOXmdE2b34zph8dIwTX9oxNbbi2qpvvleBYixhX0nwdHhzB1CJbFE+YD+Hd95+WhBBMTl/dqzCybjcxUkhbrA9Salvdv63x5B0L0FLKk/wUiMr+X3Pq8scx+c7FH/Gxe8Oil+t2bqv5Y5PIdGO8U/E7VEG6ZVSyUVrxMeOEnBn5ZKhXyERy/utVvWX0lxBDEGDbT0lyPpiJ2DrMR41cVFFFAU4HckVMgdKFLodfq3qGpC5KLflgFYTmAkTc5+8V4D4A,iv:Q8HMXC6KWvAnKnHxjtFoFHIlOscGsCJGM0LopWW2Jfg=,tag:EJCrFO+dmCDA5f198trYkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7u0qylrvurhvcaxjurqrflx2ey96lx5gzar6r8d9ctl6rzqg5gqu94ek4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzb1FGTTZXUDRBaXpoZFA1
            UEJvaDEwUnpua2hNdnU0YnY3ckpVVUYrVjI4Cmowb1lCdnVxRXFobW1oOUluTkZw
            UnZJdytlYWlZU2NoTEo0YW9UcXJtdkUKLS0tIDgreDI4eHdJUTMvaU9HU3J3akJz
            aThvSUNmTTZqZWlCeTcydndVR2hvZEEKF8C2hdPqlvrWKVt54PI4/2KLNH0cbbv9
            +ljnLiy2ZNuSvxXFMIt4N4IvTMbdcrNBetDD5KbfKILs9ZwIQO3KLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T12:55:42Z"
    mac: ENC[AES256_GCM,data:E034ORLz9sV/8csy4GpqB6tTP8YHT7JCp+Z73ZMb2Cn7D5gQFMEvlYzX/FZzvmOIanHlr+iqkl79583+cIHKAKkwFMx6lht8RL5BczY/YQqfRrauwKL/PlREqt7IylwCsF7N0iZPFzmGzfIU3a5HAgVaHlu/VXN6Y+t8ccypUuE=,iv:qTWTkXKvBtAW64vfyLoIf2phNn31XcgKBlAT8zkozek=,tag:YVus6ZMB/uMFA82eIZEpEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
