apiVersion: v1
kind: Secret
metadata:
    name: sonarr-cleanup-secrets
    namespace: default
type: Opaque
stringData:
    API_KEY: ENC[AES256_GCM,data:KQHKWdU+qMBnIk37WY38unAYGajS03C7lJkDmEdFhmo=,iv:AyJC74bqBexb7hT3rQwL3ke/xBsjeHRvDJoYUd1CzZE=,tag:OgYqBJ8qVm0LRQfNOroBrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7u0qylrvurhvcaxjurqrflx2ey96lx5gzar6r8d9ctl6rzqg5gqu94ek4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNjd6MWhoeXNKdkh2b1lv
            WWs0Tm5neFhDVTFnU3JNMU9UMmxIMTZmbFQ4CjdoZXFyVUlXR1dEZ1dqVG1zU1Jv
            MGRnV0I4b1NxaStxNU5RVkdSRHcyQmcKLS0tIDU5UGZ1ajlvY25iRWVVWnBEekJZ
            MFQzSm8za1pxQ1VPUTlmZTYwUkdIbEEKWiNmbeODNz1En3Q1ueL0rUOQq+qdTj2X
            5hudXouH9X/roNXiv7gOvnlOdXylX1m9jkbNI8R8eRofEnUt+aBPfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T07:28:23Z"
    mac: ENC[AES256_GCM,data:XRwXmqCEUeHnpVS1kZGLPaDxRNZCC1eGQ/Paj3eTLFve9Wugo3Vqkc07Wt/zN/+LtbqvTUoLIyo8t6WAdHipEEJRAm3U1ObysYHlsbEWJ3PIYI38LHRw8LZDUdcCrdxDgi6zB/0h0bnGW1KlC54nHK8wDaYTQ7oT4RLEeoMxdKw=,iv:paLOGtPCr8YItEiBPrxu9nScvad5gJt1DxuT8YNkALo=,tag:zWvFq1T+pdNUnmHFZuUV/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
