---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: maintainerr
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/jorenn92/maintainerr
      tag: latest
    env:
      TZ: "Ireland/Dublin"
    service:
      main:
        ports:
          http:
            port: 7000
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "maintainerr"
        ingressClassName: "nginx"
        hosts:
          - host: &host "maintainerr.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
            secretName: "maintainerr-tls"
    persistence:
      config:
        enabled: true
        existingClaim: maintainerr-config
        mountPath: /config
