---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: palworld-data
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
