apiVersion: v1
kind: Secret
metadata:
    name: radarr-cleanup-secrets
    namespace: default
type: Opaque
stringData:
    API_KEY: ENC[AES256_GCM,data:qGPBLHFY6lv1HVidOQrzJa/EAciqKQE9wmF3uIzZ1wE=,iv:t5zNdnVP6SaH7rPbyyv1XCd6YkM+Wh3SMVj739o41TE=,tag:wRGGzt15JB9KJJJUuxHvgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7u0qylrvurhvcaxjurqrflx2ey96lx5gzar6r8d9ctl6rzqg5gqu94ek4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVnJ5eVJrM1M1Ykp5OFNh
            Qm41WXN0OXdLRmwvaEhQSGEvNkFCa2ZPelhVCmVBS2hycEMybTJlejdENWwwa1dW
            RjBSdFpRVyt0NFVJRk56M2U0Qkg2N28KLS0tIElmUEJhcWZOUUVPRXY2Wm01QUxN
            aG9lYy85Q09ZSTRCQXdwaHU4ck1YTk0KkWedqMeukCfSZAXDk6qoV0RN7kskUYkP
            QLjXHRZB2bQcEFY8GFZKh9BvA7uyasWmQ8Bsypmy3KVZLluVneVp8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T06:57:59Z"
    mac: ENC[AES256_GCM,data:w4vMR7c8PBCEg3kP6mqq6rkF8pgpOl1CUhyhMFlRyPS2ecFgatLMZNtWTOMchEo/B9DoDEBDYE4ihsqFSW46kkS25+lcRo3y7jP9agB9u8N7qiVWJlmThJLTSKgJgoi2vkpWShXQ0xnwWjOR8Sb12pH5g1nHlOd2Vey0cpckCdg=,iv:8zuNA3PoVgGYtGE5q91q/EKrbjMu91g8uJqugSY1qzo=,tag:O7S2muM4c1kMGoKKpKeSCA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
