---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: sctx/overseerr
      tag: latest
    env:
      TZ: "Ireland/Dublin"
    service:
      main:
        ports:
          http:
            port: 5055
    ingress:
      main:
        enabled: true
        annotations:
        ingressClassName: "nginx"
        hosts:
          - host: &host "overseerr.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: overseerr-config
        mountPath: /app/config
