---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: readarr-books
  namespace: default
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: freenas.home
    path: /mnt/all/books
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-books
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 500Gi
