---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Europe/Dublin
  METALLB_LB_RANGE: 10.0.0.2-10.0.0.128
  METALLB_K8S_GATEWAY_ADDR: 10.0.0.2
  METALLB_INGRESS_ADDR: 10.0.0.3
