# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:RsI/2ck+Zrp9ZiAqNpnYrjbv2eiyMJp//ZwAcfGT2f8u50QWAw==,iv:WV1HI8EwMUv7v5l8uan7IBLb+935MUt/MXn/6aGRres=,tag:o1tZsGskiHLC1wUY7/HGOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7u0qylrvurhvcaxjurqrflx2ey96lx5gzar6r8d9ctl6rzqg5gqu94ek4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYWpmNEpacFUvNUdCM3hH
            bGMwNVVQcnZzRG44TWJFU1hRN1hmTjZOcmhnCmpQZjR3QnFZYURsaVRvQmsyd2Y4
            M0JPeVU3OEdQMUZjYk82aXpudUNLa0EKLS0tIE5DT2dVYkpJZUQ0TjFwcEdxUVhU
            UzNZVVBBS29nYWxRSHgwbVMwdGUxWFkKMzw3JyF4xXf2eqBEeeazBodUTREVJ955
            y3yp/oodpvKRH33SFd9mHdYVZbBkPXH1ctu6M3xfGFwCr1YtNvjvFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-11T22:44:45Z"
    mac: ENC[AES256_GCM,data:1exWltuyGFFFGf1rjkQQ8QSVZ0eNAlkRud2JqXOYgYR2OTTlSnU7nywFY2ukPDphFnq/IgLlaWst2TAJNICJTkjP22yQ0HJpGu/ZPbf4OXpK8Dk2QXtn5W10nO05iW8Wz9ZH1o2oAKKgONvOW8CqjCkZuDsTa/5b4iRLQ2qQ3XU=,iv:gPGx50Uyt4lfi9Zuhnf1QsU1gYMqQxgO/NOR/GXWlmE=,tag:b7ubiOVaAtCM+TStWRzY4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
