---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: default
spec:
  securityContext:
    fsGroup: 1883
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: public.ecr.aws/docker/library/eclipse-mosquitto
      tag: 2.0.18
    persistence:
      data:
        enabled: true
        existingClaim: mosquitto-data
      config:
        enabled: true
        type: configMap
        name: mosquitto-config
        mountPath: /mosquitto/config/mosquitto.conf
        subPath: mosquitto.conf
      secret:
        enabled: true
        type: secret
        name: mosquitto
        mountPath: /mosquitto/external_config/mosquitto_pwd
        subPath: mosquitto_pwd
    env:
      TZ: "Europe/Dublin"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${MQTT_LB}"
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: 1883
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 150Mi
