---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./helm-release.yaml
  - ./mosquitto-pvc.yaml
configMapGenerator:
  - name: mosquitto-config
    files:
      - mosquitto.conf=./config/mosquitto.conf
