# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: mosquitto
    namespace: default
stringData:
    mosquitto_pwd: ENC[AES256_GCM,data:VnaKF3EVXYsfnTEGIqfJJCFis5ojSbYCRfHUb3e9E4n0kmhtCePCbEvZFuU74T1p3wI9o7BoyABTdE2a7piDhgw+TaAkCvnWVuazy3LjclDbUzP2ynj+tapIDuqCPNSGkNsvUPKE5leYLccaNIRWvVgB1vCayLP9HVw=,iv:APP5S68H6S9eLdE6GiuNc1EJZuAyOHXPxLKFQiykD5A=,tag:SJ2IxgQEmo5p0s8MBpvdSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7u0qylrvurhvcaxjurqrflx2ey96lx5gzar6r8d9ctl6rzqg5gqu94ek4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WWtLZWVvd0tNaXJqSjky
            U1ljeHNaTThqcjFiTkVHUGVEQ2NFR1U2TUF3CmJVZkU0R3FIa3plNXJqQnRMNlRN
            aXhzN2RtdWxnNzM5Tzk0UGtpaDFGek0KLS0tIER3SFhHYWM2eG0xSFhPNzZwMERx
            MStYbE9kRlZhTnBURlo5ajZRZDJ3Rk0Kl+85aFBK9v3l5vDmnerk46lE0Ywh08ZM
            EHUV4i3dbRYuP0HcYuhGpdNujuIITwpuBMHDGVFrhqsadb3KM74wvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T23:08:44Z"
    mac: ENC[AES256_GCM,data:gxZRTwVr3lSIIlqm+2mZ7NxIyu3kQu2PaDOA6pJNp7yYwkC9/Yuo3noUExEDQy8R/lB1hVBXZOvf8o7SAc2V0SPe6rtk8VUA4BMt3Do/rsSUBpVgYT2VDo73TLsJZkBZ4O8b4L3ntn25GKEE879Oj+O45rXvxE0AOWevZrhTaWo=,iv:SpwSnjJP3SkMpnP2PU8UHMgz7mOtkHoTSf2wPZc1fEY=,tag:lzJByX+uZjr0gvF9ye0KQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
