# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: mosquitto
    namespace: default
stringData:
    mosquitto_pwd: ENC[AES256_GCM,data:07f9p9rvxuArts7B+fUkgsZoOVt6,iv:Qz+SfeSP0Xf7G4BTldIQ3G6RXn0jrYgBn8wPFXyo2H8=,tag:jtD1gH2lzodf6qGmRM4kbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7u0qylrvurhvcaxjurqrflx2ey96lx5gzar6r8d9ctl6rzqg5gqu94ek4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WWtLZWVvd0tNaXJqSjky
            U1ljeHNaTThqcjFiTkVHUGVEQ2NFR1U2TUF3CmJVZkU0R3FIa3plNXJqQnRMNlRN
            aXhzN2RtdWxnNzM5Tzk0UGtpaDFGek0KLS0tIER3SFhHYWM2eG0xSFhPNzZwMERx
            MStYbE9kRlZhTnBURlo5ajZRZDJ3Rk0Kl+85aFBK9v3l5vDmnerk46lE0Ywh08ZM
            EHUV4i3dbRYuP0HcYuhGpdNujuIITwpuBMHDGVFrhqsadb3KM74wvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T22:23:00Z"
    mac: ENC[AES256_GCM,data:YpbabxWNUAc07a/1l630pdL0OVQ+w3u+hw1IElcfz5y0VSlhHR3YraGo75JQ5FCzGpaFeNa1ilMr7AeB59InLZZhFfFzztziA5t+nxgG7+LsW3+gXQcHlARU9Z0v+XrWk2reJ6kYK9R2GIdq1fgfuKmzmRrv91OFdaEtQTvhoDU=,iv:Hjq+dER9OGukBlKdkWZpbpd4SEiiXMqmOOg3gcfX53c=,tag:AIOoHqbWyDp/wCemz4gE7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
