apiVersion: v1
kind: Secret
metadata:
    name: netdata-claim
    namespace: monitoring
stringData:
    NETDATA_CLAIM_TOKEN: ENC[AES256_GCM,data:7ZctaBmeBaxjP+DXKKR4fRSlbRccgKDRjnlJm2UUOIiLInj3MuUVVxpZIPeu23/DwSFcM/0qNhWToRm+m5zOC/XqAYPcPr34nIjohhrQEYyM8kt0u1eu2gDZGTgCMRiggsBGQqVwKIBDDowO6y40KjerqYnqPkXOwaiQYnT6BGm0mO+ASynr,iv:Edrlox7B4hzy1DMwIWqS3RwhapxbWzuQgcIIJD+x3aQ=,tag:CiYCPPtb91ZZgF7OL6Y85A==,type:str]
    NETDATA_CLAIM_ROOMS: ENC[AES256_GCM,data:xZswInwyuNQY2upaDv6wkpW10N2JA92FAaTorPWMRJHrkNDg,iv:ei5FIBzLMz/BsBWeD0EN98cjHyOOMpuR/hjky7hI+hk=,tag:DKst1TwQTMoWYL7uUQqC5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7u0qylrvurhvcaxjurqrflx2ey96lx5gzar6r8d9ctl6rzqg5gqu94ek4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuR2pFU3N3WWJPQ01TSHlv
            eFQyWnRZU2RVUGM0TStzN25jSmxKa0J4ejJzCkM5UlpGeGtSSGUraHRzSGJXVzcr
            alo1VmV6M3ZiZG5VclZjV2xlellmeUEKLS0tIEhrNUtQZVF3OUR2MVZYZU12Umdo
            SzRlajZNclc0ZkNIVnRNRFRzMmYrLzAKfLlws8js2YNOCJGydAWPeTYVTfdZvShG
            pQg9LMTMMz4C4U3/XU7LNtzZvloQeqN+mcVDL/XziqcKmUFke63ZtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T22:44:30Z"
    mac: ENC[AES256_GCM,data:Pn2jCP546qG5EAdhB6J9YAcR88lAyVz3HZBJNlqeiLSMTu6XprbEPgQN7MjZNDFIaBMGHHiKoDZLxmaEgHqPNhk2WO7WfvaSle7AWaXUC8P39rfYBS8hc6zBajBAxQAbbvZo/Z+u1Q7WWEEm2hCN/FzRMSY8/ArUNSjixzfNAGM=,iv:6MJm3N2j86LDfvJQgNGhLbvFYPqJRc97xLf4KcCijFc=,tag:adwxcOhvYBOAqFYPsqoy2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
