---
apiVersion: v1
kind: Service
metadata:
  name: netdata-lb
  namespace: monitoring
  annotations:
    metallb.universe.tf/loadBalancerIPs: "${NETDATA_LB}"
spec:
  type: LoadBalancer
  selector:
    app: netdata
    role: parent
  ports:
    - name: http
      port: 19999
      targetPort: 19999
      protocol: TCP
