---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/hotio/sonarr
      tag: latest
    env:
      TZ: "Ireland/Dublin"
      PUID: "351"
      PGID: "351"
    service:
      main:
        ports:
          http:
            port: 8989
      # lb:
      #   type: LoadBalancer
      #   loadBalancerIP: "${SONARR_LB}"
      #   externalTrafficPolicy: Local
      #   ports:
      #     http-lb:
      #       enabled: true
      #       port: 8989
      #       protocol: HTTP
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "television-box"
        ingressClassName: "nginx"
        hosts:
          - host: &host "sonarr.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
            secretName: "sonarr-tls"
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
        mountPath: /config
      tv:
        enabled: true
        existingClaim: sonarr-tv-shows
        mountPath: /mnt/tv_shows
