---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: tautulli/tautulli
      tag: v2.13.4
    env:
      TZ: 'Ireland/Dublin'
    service:
      main:
        ports:
          http:
            port: 8181
    ingress:
      main:
        enabled: true
        annotations:
        ingressClassName: "nginx"
        hosts:
          - host: &host "tautulli.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: tautulli-config
        mountPath: /config
