---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: audiobookshelf
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/advplyr/audiobookshelf
      tag: latest
    env:
      TZ: "Ireland/Dublin"
      PUID: "99"
      PGID: "100"
    service:
      main:
        ports:
          http:
            enabled: true
            port: 13378
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "book-open-variant"
        ingressClassName: "nginx"
        hosts:
          - host: &host "audiobookshelf.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
            secretName: "audiobookshelf-tls"
    persistence:
      config:
        enabled: true
        existingClaim: audiobookshelf-config
        mountPath: /config
      metadata:
        enabled: true
        existingClaim: audiobookshelf-metadata
        mountPath: /metadata
      books:
        enabled: true
        existingClaim: audiobookshelf-books
        mountPath: /audiobooks
