---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/hotio/radarr
      tag: latest
    env:
      TZ: "Ireland/Dublin"
      PUID: "352"
      PGID: "352"
    service:
      main:
        ports:
          http:
            port: 7878
      lb:
        type: LoadBalancer
        loadBalancerIP: "${RADARR_LB}"
        externalTrafficPolicy: Local
        ports:
          http-lb:
            enabled: true
            port: 7878
            protocol: HTTP
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "television-box"
        ingressClassName: "nginx"
        hosts:
          - host: &host "radarr.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
            secretName: "radarr-tls"
    persistence:
      config:
        enabled: true
        existingClaim: radarr-config
        mountPath: /config
      tv:
        enabled: true
        existingClaim: radarr-movies
        mountPath: /mnt/movies
