---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-movies
  namespace: default
spec:
  capacity:
    storage: 1Ti # Changed to 1 tebibyte
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: freenas.home
    path: /mnt/all/movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-movies
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Ti # Changed to 1 tebibyte
