apiVersion: v1
kind: Secret
metadata:
    name: esphome-git-ssh
    namespace: default
stringData:
    ssh-key: ENC[AES256_GCM,data:XKS3Sad3SjAXAU9Nsdf7JDqy8MG8WQzWbPtcgLRYqOSuOlimEC+WlWsnCFAlrVcF4ROq4kNDDbPL23QQ1/IAhcaSeHR8vDbppoJ1abOlqDaNji5HB1thoV8lYhBvORCncm7yq1jPZsDaxfc7NTPQ0NLE1fvGZbqZF08qiNiPprVJEeeKZQLfYKR5qhv6s8YgOFkGRtUnFDLhOr7BHD/Jd6L5byd5rqVVB202PqK00BMc5jwt/SWi2sNVNQdmmiZ3aWPMySkBF3EauBb0Yt79FTuTWOWTDrklFdZJPiILIp7jafcTSOcEArdCP0gUlwW1By0bzMb5yWyjOTh9abrxxXwpykCdAzRVpjsmczWl5rYtmofhjzk5NhXPeh5FiBpbMbh363kWLyb5H1CikaXGvomwdvj0PZ6GZbgAVHXzqVkVZfu80GHCm7l9KLbZjcEhsj1dJogePxgw/+SvlnQmOnsqWBELeJNFwZEWAoKDRVGxG3oUYNlpqKkJX/mHf3WSUe2DRmmhz5Ay9MZWesURZVZQ6aFK9RO7GibY,iv:2nvTEWhvMuSRHbyNU8ogWndGnBHdc47xQ5xjf6vfWPw=,tag:AO38bU/UH6V2nujRkaRjzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7u0qylrvurhvcaxjurqrflx2ey96lx5gzar6r8d9ctl6rzqg5gqu94ek4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEb1ZIRzVQVS91V0l6d29E
            QVFyZ09qd2pUTVJUTnRKYTQreG9ZQUhaMnlBCmNuTzJ5TjM3VW9OR2kvTTVBQ0xE
            NG5uMDV1VjBIVTRKM1hWS2FqQ1hEbkkKLS0tIDFKSzRRK0RjY1Z1ZVpsNVpWU1RO
            TEdHUWRpUFJnNmhhdUNtOGxMRC91d1kKA458xk3kWfxbqHDWMncOOcnB120gcUlf
            dJ38klQvFSOeE9MR+evbgcu7JD1TLlmwjz7EUFCUMxwDSsJFeeLHgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T21:12:24Z"
    mac: ENC[AES256_GCM,data:ESTYMxV8ldZlEQJ1l11gkaotHFzVB9uevVoIHtvL4IKN2G3F209Cmcsuhvp9TX0AUYhRxF++QeUFQgMjJ4nehuO1Z2UGUt8RnovnQAPQntFjXhBUTTV4CCwdMWyp/XKzQPlc348t7oCxwu9g79SM9bqboLvadRl1mWNWB9lMbxw=,iv:lVZnJd5yHuX0WbHucI3PGQX6FbzUvZR+gbik+0xnsnU=,tag:vrU0I8P/eC/fd8xfWShZOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
