apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: esphome
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    hostNetwork: true
    image:
      repository: esphome/esphome
      tag: latest
    env:
      TZ: "UTC"
      ESPHOME_DASHBOARD_USE_PING: "true"
    service:
      main:
        ports:
          http:
            port: 6052
          mdns:
            port: 5353
            protocol: UDP
      lb:
        type: LoadBalancer
        loadBalancerIP: "${ESPHOME_LB}"
        externalTrafficPolicy: Local
        ports:
          http-lb:
            port: 6052
          mdns-lb:
            port: 5353
            targetPort: 5353
            protocol: UDP
    ingress:
      main:
        enabled: true
        annotations:
        ingressClassName: "nginx"
        hosts:
          - host: &host "esphome.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: esphome-config
        mountPath: /config
