apiVersion: v1
kind: Secret
metadata:
    name: esphome-secrets
    namespace: default
stringData:
    secrets.yaml: ENC[AES256_GCM,data:8MksVRgeYvEb2uCPXyj2y0/BHWWe5FCggsyRd/6MikffWmH3HLQr7UA+P1PZK17GeMyh7D0uN5eep3s=,iv:v5sk49fglFQjuj6pFaRP1lIq7v7jnebFAxtRK6Jby0U=,tag:6irqc+fu+Tzz3cpz43hXSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7u0qylrvurhvcaxjurqrflx2ey96lx5gzar6r8d9ctl6rzqg5gqu94ek4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxM0c4Q3MycjNvWVlsUlVG
            ZUh3K2xZRWM1WU93amRaZmFIK1lIL3k1VGhVCjdSaFpiVlR4cmJmNjZSY2ZVaUVI
            R203bHJOdzJzSFZRTGw1N2lRdENJT2sKLS0tIFVRK2tIR2gzUllzaS9VbUNJQUUw
            LzJneGMzTG8rS0dMVE4rMUFyVzRHQWsKWS7mjRvkQYc/grGAh5OM5eOxVK0vC24o
            rV0rdL6qmzUKOwQXFI4xu1ZHaEk2KSMQ4kn7cLV/pk0y9D3foMKF0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T21:08:38Z"
    mac: ENC[AES256_GCM,data:6FM6ZskehIHKBnif6B4QXyRVuTZzVVMJjl1IIFcQyMJDg2AiW/Dr0z29/20H3XujHVjE2Oh9aH/BV62A2gGAgZmSiiJuMym8dx/+TLMbx0L/al0ZNYjbs2/XH6SLAnsV8Wvrz9NO1UNBlgRmMhYPiNlpti6BICazHAOgk8W5DnQ=,iv:U1jdgxSmdltq+g4rLVPAReD7OaiYe9FLMMRz8D21LPs=,tag:X8OMgSEliMQ8RncISdJMFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
